before:
  hooks:
    - make dependencies ui
builds:
  - main: ./cmd/run-server.go
    env:
      - CGO_ENABLED=0
    flags:
      - -a
archives:
  - replacements:
      linux: Linux
    files:
      - README.md
      - LICENSE.md
      - VERSION
      - k8s/**/*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

