apiVersion: apps/v1
kind: Deployment
metadata:
  name: pm
spec:
  selector:
    matchLabels:
      run: pm
  replicas: 1
  template:
    metadata:
      labels:
        run: pm
    spec:
      containers:
        - name: pm
          image: pm:0.0.1
          ports:
            - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: pm
  labels:
    run: pm
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    run: pm
