apiVersion: apps/v1
kind: Deployment
metadata:
  name: permission-manager-deployment
  labels:
    app: permission-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: permission-manager
  template:
    metadata:
      labels:
        app: permission-manager
    spec:
      containers:
        - name: permission-manager
          image: permission-manager:1.0.1-beta
          ports:
            - containerPort: 4000
          env:
            - name: CLUSTER_NAME
              value: "my-cluster"
            - name: CONTROL_PLANE_ADDRESS
              value: "https://192.168.64.26:8443"
