apiVersion: v1
kind: ServiceAccount
metadata:
  name: permission-manager-service-account
  namespace: permission-manager
imagePullSecrets:
  - name: sighup-gitlab-registry
---
# apiVersion: rbac.authorization.k8s.io/v1beta1
# kind: Role
# metadata:
#   name: permission-manager-role
#   namespace: permission-manager
# rules:
#   - apiGroups:
#       - "*"
#     resources:
#       - "rolebindings"
#       - "roles"
#     verbs: ["*"]
# ---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: permission-manager-cluster-role
rules:
  - apiGroups:
      - "*"
    resources:
      - "permissionmanagerusers"
      - "clusterrolebindings"
      - "clusterroles"
      - "rolebindings"
      - "roles"
      - "certificatesigningrequests"
      - "certificatesigningrequests/approval"
    verbs:
      - "*"

  - apiGroups:
      - ""
    resources:
      - "namespaces"
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: permission-manager-service-account-rolebinding
  namespace: permission-manager
roleRef:
  kind: Role
  name: permission-manager-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: permission-manager-service-account
    namespace: permission-manager
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: permission-manager-service-account-rolebinding
roleRef:
  kind: ClusterRole
  name: permission-manager-cluster-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: permission-manager-service-account
    namespace: permission-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: permission-manager
  name: permission-manager-deployment
  labels:
    app: permission-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: permission-manager
  template:
    metadata:
      labels:
        app: permission-manager
    spec:
      serviceAccountName: permission-manager-service-account
      containers:
        - name: permission-manager
          image: reg.sighup.io/sighup-products/permission-manager:1.0.0
          ports:
            - containerPort: 4000
          env:
            - name: CLUSTER_NAME
              value: "my-cluster"
            - name: CONTROL_PLANE_ADDRESS
              value: "https://192.168.64.33:8443"
            - name: BASIC_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-password-secret
                  key: password

---
apiVersion: v1
kind: Service
metadata:
  namespace: permission-manager
  name: permission-manager-service
spec:
  selector:
    app: permission-manager
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
